### ISSUE TITLE
Implement rf-cond and inline-cond

### ISSUE THREAD

**Issue by green-coder** [clojure-tw/hopen#3]
Start from the tests on the branch `rf-cond--inline-cond`.

**Comment by Odie** [comment]
Btw, why would there need to be a separate "inline" version? Shouldn't handling of these different forms all sent through the same evaluation process?

Are there instances where "block" and "inline" versions are handled differently?

**Comment by green-coder** [comment]
The block version and the inline version are different functions, accepting different parameters, different parameter types, and outputting different result.

I should not have call them using the same name from the beginning. Thank you for helping me fixing that.
